#!/bin/sh
set -eu
cd "$(dirname "$0")/.."
for dockerfile in Dockerfile tools/site/Dockerfile.test; do
  docker run --rm -i ghcr.io/hadolint/hadolint:v2.12.0@sha256:30a8fd2e785ab6176eed53f74769e04f125afb2f74a6c52aef7d463583b6d45e < "$dockerfile"
done
